// packages/ui/src/web-components/question/questions-waiting.tsx
import { defineWebComponent } from '../define/define';
import { QuestionsWaiting } from '../../components/question/questions-waiting';

interface Props extends Record<string, unknown> {
  /** How many questions still have no answer. */
  count?: number;
  /** How many questions the call asked in all. */
  total?: number;
  /** Text of the reopen control. */
  reopenLabel?: string;
}

interface Events extends Record<string, unknown> {
  /** The reopen control was pressed. The host brings the panel back and calls its `focus()`. */
  'kai-reopen': Record<string, never>;
}
// Meant for the prompt input's `above` region, after the panel was dismissed with questions unanswered.
/**
 * The quiet "N of M questions waiting" line with a Reopen control.
 */
defineWebComponent<Props, Events>('kai-questions-waiting', {
  count: 0,
  total: 0,
  reopenLabel: undefined,
}, (props, { dispatch }) => (
  <>
    <style>{':host{display:block}:host([hidden]){display:none}'}</style>
    <QuestionsWaiting
      count={Number(props.count) || 0}
      total={Number(props.total) || 0}
      reopenLabel={props.reopenLabel as string | undefined}
      onReopen={() => dispatch('kai-reopen', {})}
    />
  </>
));

// packages/ui/src/components/question/questions-waiting.tsx
import { type JSX } from 'solid-js';
import { cn } from '../../utils/cn';

export interface QuestionsWaitingProps {
  /** Questions still without an answer. */
  count: number;
  /** All the questions of the call. */
  total: number;
  /** The control's text. Default "Reopen". */
  reopenLabel?: string;
  onReopen?: () => void;
  class?: string;
}

/** The quiet "N of M questions waiting · Reopen" line the composer carries after "Let's chat". */
export function QuestionsWaiting(props: QuestionsWaitingProps): JSX.Element {
  const noun = () => (props.total === 1 ? 'question' : 'questions');
  const text = () => (props.total > 1 ? `${props.count} of ${props.total} ${noun()} waiting` : `${props.count} ${noun()} waiting`);
  return (
    <div class={cn('flex items-center gap-2 text-meta text-muted-foreground', props.class)} role="status">
      <span>{text()}</span>
      <button
        type="button"
        onClick={() => props.onReopen?.()}
        class="rounded-md px-1 text-foreground underline underline-offset-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      >
        {props.reopenLabel ?? 'Reopen'}
      </button>
    </div>
  );
}
