// examples/vue/src/App.vue
<!--
  kitn-chat Vue 3 example — using web components natively.

  Vue can bind to custom-element DOM properties with the `.prop` modifier:
    :prop.prop="value"  — sets the DOM *property* (not a stringified attribute);
                          essential for passing arrays/objects into Shadow-DOM
                          web components.

  CustomEvents are listened to with @event="handler":
    @submit="onSubmit"  — `$event` is the raw CustomEvent; `.detail` carries the
                          payload.

  vite.config.ts declares `isCustomElement: (tag) => tag.startsWith('kitn-')`
  so Vue treats kitn-* tags as native custom elements rather than Vue components
  (no "Unknown custom element" warnings).

  `@kitnai/chat/elements` is imported once (main.ts side-effect) to register
  the custom elements globally — BEFORE this component mounts.
-->

<script setup lang="ts">
import { ref, computed, reactive } from 'vue';

// Shared sample data (also used by React / Angular examples).
import {
  SAMPLE_GROUPS,
  SAMPLE_CONVERSATIONS,
  SAMPLE_MESSAGES,
  SAMPLE_MODELS,
  SAMPLE_CONTEXT,
  SAMPLE_SUGGESTIONS,
  SAMPLE_SLASH_COMMANDS,
  type SampleMessage,
  type SampleConversation,
} from '../../shared/sample-data';

// ── Types ──────────────────────────────────────────────────────────────────────

type Theme = 'light' | 'dark' | 'auto';
type ChatMessage = SampleMessage;

// ── Helpers ────────────────────────────────────────────────────────────────────

function generateId(): string {
  return Math.random().toString(36).slice(2, 9);
}

function buildReply(text: string): string {
  return `Thanks for your message!\n\n> ${text}\n\nThis canned reply was appended to the \`messages\` property via Vue refs — proving array round-tripping through the web component binding.`;
}

/** "Streams" a reply word-by-word, calling onChunk on each tick. */
function streamReply(
  fullText: string,
  onChunk: (partial: string, done: boolean) => void,
): () => void {
  const words = fullText.split(' ');
  let i = 0;
  const timer = setInterval(() => {
    i += 1;
    const partial = words.slice(0, i).join(' ');
    const done = i >= words.length;
    onChunk(partial, done);
    if (done) clearInterval(timer);
  }, 40);
  return () => clearInterval(timer);
}

const SUN_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/></svg>';
const MOON_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg>';

// ── Reactive state ─────────────────────────────────────────────────────────────

const theme = ref<Theme>('auto');
const conversations = ref<SampleConversation[]>(SAMPLE_CONVERSATIONS);
const activeId = ref<string>('c-1');
const allMessages = reactive<Record<string, ChatMessage[]>>(
  // Deep clone so mutations don't affect the imported constant
  Object.fromEntries(
    Object.entries(SAMPLE_MESSAGES).map(([k, v]) => [k, [...v]]),
  ),
);
const currentModel = ref<string>('sonnet');
const loading = ref<boolean>(false);
const toast = ref<string | null>(null);
const draftSubmissions = ref<string[]>([]);

// ── Derived ────────────────────────────────────────────────────────────────────

/** Messages for the active conversation. */
const messages = computed(() => allMessages[activeId.value] ?? []);

/** Is the effective theme dark right now? */
const isDark = computed(() => {
  const t = theme.value;
  const systemDark =
    typeof window !== 'undefined' &&
    window.matchMedia('(prefers-color-scheme: dark)').matches;
  return t === 'dark' || (t === 'auto' && systemDark);
});

const borderColor = computed(() =>
  isDark.value ? '#27272a' : '#e5e5e5',
);
const appBackground = computed(() =>
  isDark.value ? '#0a0a0b' : '#ffffff',
);
const appColor = computed(() =>
  isDark.value ? '#fafafa' : '#18181b',
);
const themeIconHtml = computed(() =>
  isDark.value ? MOON_SVG : SUN_SVG,
);

// ── Static data passed as .prop bindings to the web components ─────────────────

const groups = SAMPLE_GROUPS;
const models = SAMPLE_MODELS;
const context = SAMPLE_CONTEXT;
const suggestions = SAMPLE_SUGGESTIONS;
const slashCommands = SAMPLE_SLASH_COMMANDS;

// ── Helpers ────────────────────────────────────────────────────────────────────

function showToast(msg: string): void {
  toast.value = msg;
  setTimeout(() => { toast.value = null; }, 1600);
}

function toggleTheme(): void {
  const wasDark = isDark.value;
  theme.value = wasDark ? 'light' : 'dark';
}

// ── kitn-chat-workspace event handlers ─────────────────────────────────────────

/**
 * @submit — fired when the user sends a message.
 * Vue listens to CustomEvents with @event="handler".
 * `$event` is the raw Event; cast to CustomEvent to access `.detail`.
 */
function onSubmit(event: Event): void {
  const { value, attachments } = ((event as CustomEvent).detail ?? {}) as {
    value?: string;
    attachments?: unknown[];
  };
  const text = (value ?? '').trim();
  if (!text && !(attachments ?? []).length) return;

  const userMsg: ChatMessage = { id: 'u' + generateId(), role: 'user', content: text };
  const replyId = 'a' + generateId();
  const id = activeId.value;

  // Append user message + empty assistant placeholder.
  if (!allMessages[id]) allMessages[id] = [];
  allMessages[id] = [
    ...allMessages[id],
    userMsg,
    { id: replyId, role: 'assistant', content: '' },
  ];
  loading.value = true;

  streamReply(buildReply(text || 'your attachment'), (partial, done) => {
    allMessages[id] = (allMessages[id] ?? []).map((m) =>
      m.id === replyId
        ? {
            ...m,
            content: partial,
            actions: done
              ? (['copy', 'like', 'dislike', 'regenerate'] as ChatMessage['actions'])
              : undefined,
          }
        : m,
    );
    if (done) loading.value = false;
  });
}

/**
 * @messageaction — copy, like, dislike, regenerate actions on messages.
 */
async function onMessageAction(event: Event): Promise<void> {
  const { messageId, action } = ((event as CustomEvent).detail ?? {}) as {
    messageId: string;
    action: string;
  };
  const id = activeId.value;
  const msgs = allMessages[id] ?? [];
  const msg = msgs.find((m) => m.id === messageId);
  if (!msg) return;

  if (action === 'copy') {
    try {
      await navigator.clipboard.writeText(msg.content);
      showToast('Copied to clipboard');
    } catch {
      showToast('Copy failed');
    }
  } else if (action === 'like') {
    showToast('Glad it helped!');
  } else if (action === 'dislike') {
    showToast('Thanks — noted.');
  } else if (action === 'regenerate') {
    const idx = msgs.findIndex((m) => m.id === messageId);
    const replyId = 'a' + generateId();
    allMessages[id] = [
      ...msgs.slice(0, idx),
      { id: replyId, role: 'assistant' as const, content: '' },
    ];
    loading.value = true;
    streamReply(buildReply('regenerated answer'), (partial, done) => {
      allMessages[id] = (allMessages[id] ?? []).map((m) =>
        m.id === replyId
          ? {
              ...m,
              content: partial,
              actions: done
                ? (['copy', 'like', 'dislike', 'regenerate'] as ChatMessage['actions'])
                : undefined,
            }
          : m,
      );
      if (done) loading.value = false;
    });
  }
}

/**
 * @modelchange — user switched the active model.
 */
function onModelChange(event: Event): void {
  const { modelId } = ((event as CustomEvent).detail ?? {}) as { modelId: string };
  currentModel.value = modelId;
  showToast(
    `Model → ${SAMPLE_MODELS.find((m) => m.id === modelId)?.name ?? modelId}`,
  );
}

/**
 * @conversationselect — user clicked a conversation in the sidebar.
 */
function onConversationSelect(event: Event): void {
  const { id } = ((event as CustomEvent).detail ?? {}) as { id: string };
  activeId.value = id;
  document.body.classList.remove('sidebar-open');
}

/**
 * @newchat — user clicked "New chat" in the sidebar.
 */
function onNewChat(): void {
  const id = 'c-' + generateId();
  conversations.value = [
    {
      id,
      title: 'New chat',
      groupId: 'g-work',
      scope: { type: 'collection' as const },
      messageCount: 0,
      lastMessageAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    ...conversations.value,
  ];
  allMessages[id] = [];
  activeId.value = id;
  document.body.classList.remove('sidebar-open');
}

/**
 * @sidebartoggle — hamburger / toggle from within the workspace.
 */
function onSidebarToggle(): void {
  document.body.classList.toggle('sidebar-open');
}

// ── Standalone kitn-prompt-input handler ───────────────────────────────────────

function onStandaloneSubmit(event: Event): void {
  const { value } = ((event as CustomEvent).detail ?? {}) as { value?: string };
  const text = (value ?? '').trim();
  if (!text) return;
  draftSubmissions.value = [text, ...draftSubmissions.value].slice(0, 5);
}
</script>

<template>
  <!--
    kitn-chat Vue 3 example template.

    Key Vue web-component patterns:
      :prop.prop="value"   — the `.prop` modifier sets the DOM *property*
                             (not a stringified attribute); required for passing
                             arrays / objects into Shadow-DOM custom elements.
      @event="handler"     — listens for CustomEvents by lowercase event name;
                             `$event` is the raw Event, cast inside the handler.
  -->
  <div
    class="app-shell"
    :style="{ background: appBackground, color: appColor }"
  >
    <!-- Top bar -->
    <header class="topbar" :style="{ borderBottom: '1px solid ' + borderColor }">
      <span class="topbar-brand">
        <img src="../../shared/logo.svg" alt="" width="20" height="20" />
        kitn-chat &middot; Vue example (web components)
      </span>

      <button
        @click="toggleTheme"
        aria-label="Toggle light/dark"
        class="theme-btn"
        :style="{
          border: '1px solid ' + (isDark ? '#3f3f46' : '#d4d4d8'),
          background: isDark ? '#18181b' : '#fff',
          color: isDark ? '#fafafa' : '#18181b',
        }"
        v-html="themeIconHtml"
      ></button>
    </header>

    <!-- Main area: the flagship <kitn-chat-workspace> element.
         :prop.prop sets DOM properties; @event listens for CustomEvents.
         The `.prop` modifier is critical — without it Vue would stringify
         arrays/objects as attributes and the elements would receive "[object Object]". -->
    <div class="main-area">
      <!--
        <kitn-chat-workspace> is the batteries-included shell: sidebar +
        conversation list + chat panel + resize handle, all in one element.

        Property bindings (:prop.prop):
          - :groups.prop          SampleGroup[]        — sidebar group headers
          - :conversations.prop   SampleConversation[] — sidebar conversation list
          - :activeId.prop        string               — highlighted conversation
          - :messages.prop        SampleMessage[]      — chat message thread
          - :models.prop          SampleModel[]        — model picker options
          - :currentModel.prop    string               — selected model id
          - :context.prop         object               — token-usage context meter
          - :suggestions.prop     string[]             — prompt suggestions
          - :slashCommands.prop   object[]             — slash-command items
          - :loading.prop         boolean              — streaming / loading state
          - :theme.prop           'light'|'dark'|'auto'

        Event bindings (@event):
          - @submit               — user sends a message
          - @messageaction        — copy / like / dislike / regenerate
          - @modelchange          — model picker changed
          - @conversationselect   — sidebar item clicked
          - @newchat              — "New chat" button clicked
          - @sidebartoggle        — hamburger / sidebar toggle
      -->
      <kitn-chat-workspace
        :groups.prop="groups"
        :conversations.prop="conversations"
        :activeId.prop="activeId"
        :messages.prop="messages"
        :models.prop="models"
        :currentModel.prop="currentModel"
        :context.prop="context"
        :suggestions.prop="suggestions"
        :slashCommands.prop="slashCommands"
        :loading.prop="loading"
        :theme.prop="theme"
        @submit="onSubmit"
        @messageaction="onMessageAction"
        @modelchange="onModelChange"
        @conversationselect="onConversationSelect"
        @newchat="onNewChat"
        @sidebartoggle="onSidebarToggle"
        style="flex: 1; min-height: 0;"
      ></kitn-chat-workspace>
    </div>

    <!-- Standalone <kitn-prompt-input> — proves a leaf element works on its own. -->
    <div class="standalone-section" :style="{ borderTop: '1px solid ' + borderColor }">
      <div class="standalone-label">
        Standalone &lt;kitn-prompt-input&gt; (try typing <code>/</code> for slash commands):
      </div>
      <kitn-prompt-input
        placeholder="Standalone prompt input…"
        :slashCommands.prop="slashCommands"
        :theme.prop="theme"
        @submit="onStandaloneSubmit"
      ></kitn-prompt-input>
      <ul v-if="draftSubmissions.length > 0" class="draft-list">
        <li v-for="d in draftSubmissions" :key="d">submitted: {{ d }}</li>
      </ul>
    </div>

    <!-- Toast notification -->
    <div v-if="toast" class="toast">{{ toast }}</div>
  </div>
</template>

<style>
/* ── App shell ───────────────────────────────────────────────────────────── */

.app-shell {
  display: flex;
  flex-direction: column;
  height: 100vh;
  font-family: system-ui, sans-serif;
}

/* ── Top bar ─────────────────────────────────────────────────────────────── */

.topbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 48px;
  padding: 0 14px;
  flex-shrink: 0;
}

.topbar-brand {
  display: flex;
  align-items: center;
  gap: 8px;
  font-weight: 700;
  font-size: 14px;
}

/* ── Theme toggle button ─────────────────────────────────────────────────── */

.theme-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 34px;
  height: 34px;
  border-radius: 9px;
  cursor: pointer;
}

/* ── Main area ───────────────────────────────────────────────────────────── */

.main-area {
  display: flex;
  flex: 1;
  min-height: 0;
}

/* ── Standalone prompt input section ─────────────────────────────────────── */

.standalone-section {
  padding: 10px 14px;
  flex-shrink: 0;
}

.standalone-label {
  font-size: 12px;
  opacity: 0.7;
  margin-bottom: 6px;
}

.draft-list {
  font-size: 12px;
  opacity: 0.7;
  margin: 8px 0 0;
  padding-left: 18px;
}

/* ── Toast notification ──────────────────────────────────────────────────── */

.toast {
  position: fixed;
  bottom: 18px;
  left: 50%;
  transform: translateX(-50%);
  background: #18181b;
  color: #fafafa;
  font: 500 13px system-ui, sans-serif;
  padding: 8px 14px;
  border-radius: 8px;
  z-index: 50;
  pointer-events: none;
}
</style>

// examples/angular/src/app/app.component.ts
/**
 * kc-chat Angular example — using web components natively.
 *
 * Angular can bind to custom-element DOM properties with [prop]="value" and
 * listen to CustomEvents with (eventname)="handler($event)".  No wrappers or
 * adapters are needed — this is the whole point of the example.
 *
 * Key patterns demonstrated:
 *   - [groups], [conversations], [activeId], [messages], [models], [currentModel]
 *     set DOM *properties* (not attributes) — essential for passing objects/arrays
 *     to Shadow-DOM web components.
 *   - (conversationselect), (submit), (modelchange), (sidebartoggle) listen to the
 *     kit's CustomEvents; `($event as CustomEvent).detail` carries the payload.
 *   - CUSTOM_ELEMENTS_SCHEMA tells Angular to allow unknown `kitn-*` element tags.
 *   - `@kitnai/chat/elements` is imported once (main.ts side-effect) to register
 *     the custom elements globally.
 */

import {
  Component,
  signal,
  computed,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';

// Shared sample data (also used by React / Solid examples).
import {
  SAMPLE_GROUPS,
  SAMPLE_CONVERSATIONS,
  SAMPLE_MESSAGES,
  SAMPLE_MODELS,
  SAMPLE_CONTEXT,
  SAMPLE_SUGGESTIONS,
  SAMPLE_SLASH_COMMANDS,
  type SampleMessage,
  type SampleConversation,
} from '../../../shared/sample-data';

// ── Types ─────────────────────────────────────────────────────────────────────

type Theme = 'light' | 'dark' | 'auto';
type ChatMessage = SampleMessage;

// ── Helpers ───────────────────────────────────────────────────────────────────

function generateId(): string {
  return Math.random().toString(36).slice(2, 9);
}

function buildReply(text: string): string {
  return `Thanks for your message!\n\n> ${text}\n\nThis canned reply was appended to the \`messages\` property via Angular signals — proving array round-tripping through the web component binding.`;
}

/** "Streams" a reply word-by-word, calling onChunk on each tick. */
function streamReply(
  fullText: string,
  onChunk: (partial: string, done: boolean) => void,
): () => void {
  const words = fullText.split(' ');
  let i = 0;
  const timer = setInterval(() => {
    i += 1;
    const partial = words.slice(0, i).join(' ');
    const done = i >= words.length;
    onChunk(partial, done);
    if (done) clearInterval(timer);
  }, 40);
  return () => clearInterval(timer);
}

const SUN_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2"/><path d="M12 20v2"/><path d="m4.93 4.93 1.41 1.41"/><path d="m17.66 17.66 1.41 1.41"/><path d="M2 12h2"/><path d="M20 12h2"/><path d="m6.34 17.66-1.41 1.41"/><path d="m19.07 4.93-1.41 1.41"/></svg>';
const MOON_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/></svg>';

// ── Component ─────────────────────────────────────────────────────────────────

@Component({
  selector: 'app-root',
  standalone: true,
  // CUSTOM_ELEMENTS_SCHEMA is required so Angular accepts the kitn-* tags
  // without treating them as unknown Angular components.
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  // ── Signals (reactive state) ───────────────────────────────────────────────

  theme = signal<Theme>('auto');
  conversations = signal<SampleConversation[]>(SAMPLE_CONVERSATIONS);
  activeId = signal<string>('c-1');
  allMessages = signal<Record<string, ChatMessage[]>>(SAMPLE_MESSAGES);
  currentModel = signal<string>('sonnet');
  loading = signal<boolean>(false);
  toast = signal<string | null>(null);
  draftSubmissions = signal<string[]>([]);

  // Derived — messages for the active conversation.
  messages = computed(() => this.allMessages()[this.activeId()] ?? []);

  // Derived — is the current effective theme dark?
  isDark = computed(() => {
    const t = this.theme();
    const systemDark =
      typeof window !== 'undefined' &&
      window.matchMedia('(prefers-color-scheme: dark)').matches;
    return t === 'dark' || (t === 'auto' && systemDark);
  });

  // Static data passed as [properties] to the web components.
  readonly groups = SAMPLE_GROUPS;
  readonly models = SAMPLE_MODELS;
  readonly context = SAMPLE_CONTEXT;
  readonly suggestions = SAMPLE_SUGGESTIONS;
  readonly slashCommands = SAMPLE_SLASH_COMMANDS;

  // ── Helpers ────────────────────────────────────────────────────────────────

  get themeIconHtml(): string {
    return this.isDark() ? MOON_SVG : SUN_SVG;
  }

  get borderColor(): string {
    return this.isDark() ? '#27272a' : '#e5e5e5';
  }

  get appBackground(): string {
    return this.isDark() ? '#0a0a0b' : '#ffffff';
  }

  get appColor(): string {
    return this.isDark() ? '#fafafa' : '#18181b';
  }

  private showToast(msg: string): void {
    this.toast.set(msg);
    setTimeout(() => this.toast.set(null), 1600);
  }

  toggleTheme(): void {
    const prev = this.theme();
    const wasDark = prev === 'dark' || (prev === 'auto' && this.isDark());
    this.theme.set(wasDark ? 'light' : 'dark');
  }

  // ── kc-workspace event handlers ────────────────────────────────────

  /**
   * `(submit)` — fired when the user sends a message.
   * Angular binds CustomEvents by lowercase event name on the element.
   * `$event` is the raw CustomEvent; `.detail` carries the payload.
   */
  onSubmit(event: Event): void {
    const { value, attachments } = ((event as CustomEvent).detail ?? {}) as {
      value?: string;
      attachments?: unknown[];
    };
    const text = (value ?? '').trim();
    if (!text && !(attachments ?? []).length) return;

    const userMsg: ChatMessage = { id: 'u' + generateId(), role: 'user', content: text };
    const replyId = 'a' + generateId();
    const id = this.activeId();

    // Append user message + empty assistant placeholder.
    this.allMessages.update((prev) => ({
      ...prev,
      [id]: [...(prev[id] ?? []), userMsg, { id: replyId, role: 'assistant', content: '' }],
    }));
    this.loading.set(true);

    streamReply(buildReply(text || 'your attachment'), (partial, done) => {
      this.allMessages.update((prev) => ({
        ...prev,
        [id]: (prev[id] ?? []).map((m) =>
          m.id === replyId
            ? {
                ...m,
                content: partial,
                actions: done
                  ? (['copy', 'like', 'dislike', 'regenerate'] as ChatMessage['actions'])
                  : undefined,
              }
            : m,
        ),
      }));
      if (done) this.loading.set(false);
    });
  }

  /**
   * `(messageaction)` — copy, like, dislike, regenerate actions on messages.
   */
  async onMessageAction(event: Event): Promise<void> {
    const { messageId, action } = ((event as CustomEvent).detail ?? {}) as {
      messageId: string;
      action: string;
    };
    const id = this.activeId();
    const msgs = this.allMessages()[id] ?? [];
    const msg = msgs.find((m) => m.id === messageId);
    if (!msg) return;

    if (action === 'copy') {
      try {
        await navigator.clipboard.writeText(msg.content);
        this.showToast('Copied to clipboard');
      } catch {
        this.showToast('Copy failed');
      }
    } else if (action === 'like') {
      this.showToast('Glad it helped!');
    } else if (action === 'dislike') {
      this.showToast('Thanks — noted.');
    } else if (action === 'regenerate') {
      const idx = msgs.findIndex((m) => m.id === messageId);
      const replyId = 'a' + generateId();
      this.allMessages.update((prev) => ({
        ...prev,
        [id]: [...(prev[id] ?? []).slice(0, idx), { id: replyId, role: 'assistant' as const, content: '' }],
      }));
      this.loading.set(true);
      streamReply(buildReply('regenerated answer'), (partial, done) => {
        this.allMessages.update((prev) => ({
          ...prev,
          [id]: (prev[id] ?? []).map((m) =>
            m.id === replyId
              ? {
                  ...m,
                  content: partial,
                  actions: done
                    ? (['copy', 'like', 'dislike', 'regenerate'] as ChatMessage['actions'])
                    : undefined,
                }
              : m,
          ),
        }));
        if (done) this.loading.set(false);
      });
    }
  }

  /**
   * `(modelchange)` — user switched the active model.
   */
  onModelChange(event: Event): void {
    const { modelId } = ((event as CustomEvent).detail ?? {}) as { modelId: string };
    this.currentModel.set(modelId);
    this.showToast(
      `Model → ${SAMPLE_MODELS.find((m) => m.id === modelId)?.name ?? modelId}`,
    );
  }

  /**
   * `(conversationselect)` — user clicked a conversation in the sidebar.
   */
  onConversationSelect(event: Event): void {
    const { id } = ((event as CustomEvent).detail ?? {}) as { id: string };
    this.activeId.set(id);
    document.body.classList.remove('sidebar-open');
  }

  /**
   * `(newchat)` — user clicked "New chat" in the sidebar.
   */
  onNewChat(): void {
    const id = 'c-' + generateId();
    this.conversations.update((prev) => [
      {
        id,
        title: 'New chat',
        groupId: 'g-work',
        scope: { type: 'collection' as const },
        messageCount: 0,
        lastMessageAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      ...prev,
    ]);
    this.allMessages.update((prev) => ({ ...prev, [id]: [] }));
    this.activeId.set(id);
    document.body.classList.remove('sidebar-open');
  }

  /**
   * `(sidebartoggle)` — hamburger / toggle from within the workspace.
   */
  onSidebarToggle(): void {
    document.body.classList.toggle('sidebar-open');
  }

  // ── Standalone kc-prompt-input handler ──────────────────────────────────

  onStandaloneSubmit(event: Event): void {
    const { value } = ((event as CustomEvent).detail ?? {}) as { value?: string };
    const text = (value ?? '').trim();
    if (!text) return;
    this.draftSubmissions.update((prev) => [text, ...prev].slice(0, 5));
  }
}

<!--
  kc-chat Angular example template.

  Key Angular web-component patterns:
    [prop]="value"    — sets the DOM *property* (not an attribute string); this is
                        how you pass arrays/objects into Shadow-DOM custom elements.
    (eventname)="fn($event)"  — listens for CustomEvents; Angular matches by the
                        lowercase event name.  `($event as CustomEvent).detail`
                        carries the payload (handled in the component class).
-->

<div
  class="app-shell"
  [style.background]="appBackground"
  [style.color]="appColor"
>
  <!-- Top bar -->
  <header class="topbar" [style.borderBottom]="'1px solid ' + borderColor">
    <span class="topbar-brand">
      <img src="../shared/logo.svg" alt="" width="20" height="20" />
      kc-chat · Angular example (web components)
    </span>

    <button
      (click)="toggleTheme()"
      aria-label="Toggle light/dark"
      class="theme-btn"
      [style.border]="'1px solid ' + (isDark() ? '#3f3f46' : '#d4d4d8')"
      [style.background]="isDark() ? '#18181b' : '#fff'"
      [style.color]="isDark() ? '#fafafa' : '#18181b'"
      [innerHTML]="themeIconHtml"
    ></button>
  </header>

  <!-- Main area: the flagship <kc-workspace> element.
       [prop] sets DOM properties; (event) listens for CustomEvents. -->
  <div class="main-area">
    <!--
      <kc-workspace> is the batteries-included shell: sidebar +
      conversation list + chat panel + resize handle, all in one element.

      Property bindings ([prop]):
        - [groups]          SampleGroup[]        — sidebar group headers
        - [conversations]   SampleConversation[] — sidebar conversation list
        - [activeId]        string               — highlighted conversation
        - [messages]        SampleMessage[]      — chat message thread
        - [models]          SampleModel[]        — model picker options
        - [currentModel]    string               — selected model id
        - [context]         object               — token-usage context meter
        - [suggestions]     string[]             — prompt suggestions
        - [slashCommands]   object[]             — slash-command items
        - [loading]         boolean              — streaming / loading state
        - [theme]           'light'|'dark'|'auto'

      Event bindings ((event)):
        - (submit)              — user sends a message
        - (messageaction)       — copy / like / dislike / regenerate
        - (modelchange)         — model picker changed
        - (conversationselect)  — sidebar item clicked
        - (newchat)             — "New chat" button clicked
        - (sidebartoggle)       — hamburger / sidebar toggle
    -->
    <kc-workspace
      [groups]="groups"
      [conversations]="conversations()"
      [activeId]="activeId()"
      [messages]="messages()"
      [models]="models"
      [currentModel]="currentModel()"
      [context]="context"
      [suggestions]="suggestions"
      [slashCommands]="slashCommands"
      [loading]="loading()"
      [theme]="theme()"
      (submit)="onSubmit($event)"
      (messageaction)="onMessageAction($event)"
      (modelchange)="onModelChange($event)"
      (conversationselect)="onConversationSelect($event)"
      (newchat)="onNewChat()"
      (sidebartoggle)="onSidebarToggle()"
      style="flex: 1; min-height: 0;"
    ></kc-workspace>
  </div>

  <!-- Standalone <kc-prompt-input> — proves a leaf element works on its own. -->
  <div class="standalone-section" [style.borderTop]="'1px solid ' + borderColor">
    <div class="standalone-label">
      Standalone &lt;kc-prompt-input&gt; (try typing <code>/</code> for slash commands):
    </div>
    <kc-prompt-input
      placeholder="Standalone prompt input…"
      [slashCommands]="slashCommands"
      [theme]="theme()"
      (submit)="onStandaloneSubmit($event)"
    ></kc-prompt-input>
    @if (draftSubmissions().length > 0) {
      <ul class="draft-list">
        @for (d of draftSubmissions(); track d) {
          <li>submitted: {{ d }}</li>
        }
      </ul>
    }
  </div>

  <!-- Toast notification -->
  @if (toast()) {
    <div class="toast">{{ toast() }}</div>
  }
</div>
