// src/elements/skeleton.tsx
import { Skeleton, type SkeletonVariant } from '../ui/skeleton';
import { defineWebComponent } from './define';

interface Props extends Record<string, unknown> {
  /** `text` (one or more lines), `rect` (a block), or `circle` (round).
   *  Defaults to `text`. */
  variant?: SkeletonVariant;
  /** CSS width (e.g. `'12rem'`, `'60%'`). Defaults to full width (responsive);
   *  for `circle` it is the diameter. */
  width?: string;
  /** CSS height. Defaults per variant (a text line height; circle = width). */
  height?: string;
  /** `text` only: number of lines; the last is shorter. Defaults to 1. */
  lines?: number;
}

/**
 * `<kai-skeleton>` — a pulsing loading placeholder that preserves layout while
 * content arrives. Responsive by default (fills its container's width). It is
 * prop-driven because utility classes can't cross the shadow boundary: pick a
 * `variant` and optionally set `width` / `height` / `lines`.
 *
 * ```html
 * <kai-skeleton variant="text" lines="3"></kai-skeleton>
 * <kai-skeleton variant="circle" width="2.5rem"></kai-skeleton>
 * <kai-skeleton variant="rect" height="10rem"></kai-skeleton>
 * ```
 * Recolor by overriding the `--color-muted` token.
 */
defineWebComponent<Props>('kai-skeleton', {
  variant: 'text',
  width: undefined,
  height: undefined,
  lines: undefined,
}, (props) => (
  <>
    <style>{':host{display:block}'}</style>
    <Skeleton
      variant={props.variant ?? 'text'}
      width={props.width}
      height={props.height}
      lines={props.lines != null ? Number(props.lines) : undefined}
    />
  </>
));

// src/ui/skeleton.tsx
import { type JSX, splitProps, For, Show } from 'solid-js';
import { cn } from '../utils/cn';

export type SkeletonVariant = 'text' | 'rect' | 'circle';

export interface SkeletonProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** Shape preset. `text` = one or more lines; `rect` = a block; `circle` =
   *  round. Omit for the bare, class-driven block (size it with utility classes
   *  yourself — the original low-level usage). */
  variant?: SkeletonVariant;
  /** CSS width (a number is treated as px). With a `variant` and no width it
   *  fills its container (responsive); for `circle` it is the diameter. */
  width?: string | number;
  /** CSS height (a number is treated as px). Defaults per variant. */
  height?: string | number;
  /** `text` only: how many lines to render (the last is shorter). Default 1. */
  lines?: number;
}

const len = (v?: string | number) => (typeof v === 'number' ? `${v}px` : v);

const rounding = (variant?: SkeletonVariant) =>
  variant === 'circle' ? 'rounded-full' : variant === 'text' ? 'rounded' : 'rounded-md';

function Skeleton(props: SkeletonProps) {
  const [local, rest] = splitProps(props, ['class', 'variant', 'width', 'height', 'lines', 'style']);

  const hasWidth = () => local.width != null;
  const hasHeight = () => local.height != null;
  // The responsive default applies only to the variant API; bare class-driven
  // usage is left untouched so `<Skeleton class="h-4 w-64" />` keeps working.
  const fills = () => !hasWidth() && local.variant != null && local.variant !== 'circle';

  const blockStyle = (shortLast: boolean): JSX.CSSProperties => {
    const style: JSX.CSSProperties = typeof local.style === 'object' && local.style ? { ...local.style } : {};
    if (local.variant === 'circle') {
      const d = len(local.width) ?? len(local.height) ?? '2.5rem';
      style.width = d;
      style.height = d;
      return style;
    }
    if (shortLast) style.width = '70%';
    else if (hasWidth()) style.width = len(local.width);
    if (hasHeight()) style.height = len(local.height);
    else if (local.variant === 'text') style.height = '0.75rem';
    return style;
  };

  const block = (shortLast = false) => (
    <div
      class={cn('animate-pulse bg-muted', rounding(local.variant), fills() && 'w-full', local.class)}
      style={blockStyle(shortLast)}
      {...rest}
    />
  );

  const lineCount = () => (local.variant === 'text' ? Math.max(1, local.lines ?? 1) : 1);

  return (
    <Show when={lineCount() > 1} fallback={block()}>
      <div class="flex w-full flex-col gap-2">
        <For each={Array.from({ length: lineCount() })}>{(_, i) => block(i() === lineCount() - 1)}</For>
      </div>
    </Show>
  );
}

export { Skeleton };
