// packages/ui/src/components/screen.tsx
import { createEffect, createSignal, onCleanup, Show, type Accessor, type JSX } from 'solid-js';
import { ArrowLeft } from 'lucide-solid';
import { cn } from '../utils/cn';
import { createPresence } from '../ui/overlay';

/** Imperative open controller, handed to a parent (the kai-screen facade) via
 *  `controllerRef` so it can drive/observe open state with `wireDisclosure`. */
export interface ScreenController {
  open: Accessor<boolean>;
  setOpen: (v: boolean) => void;
}

export interface ScreenProps {
  /** The screen body. */
  children?: JSX.Element;
  /** Header title text. A projected `title` slot overrides this. */
  title?: JSX.Element;
  /** Header title slot content (the facade's `<slot name="title" />`). Overrides `title`. */
  titleSlot?: JSX.Element;
  /** Header trailing cluster (the facade's `<slot name="actions" />`). */
  actions?: JSX.Element;
  /** Controlled open state. When set, the component never changes it itself;
   *  drive it from `onOpenChange`. Omit for uncontrolled (internal) state. */
  open?: boolean;
  /** Initial open state when uncontrolled. */
  defaultOpen?: boolean;
  /** Show the back button (default true). */
  back?: boolean;
  /** Skip marking sibling elements inert/aria-hidden while open. */
  noInert?: boolean;
  /** The custom-element host, whose siblings get inert-ed while open. */
  host?: () => HTMLElement | undefined;
  /** Fires whenever open wants to change (back button / method). */
  onOpenChange?: (open: boolean) => void;
  /** Back navigation intent: the back button or Escape. */
  onBack?: () => void;
  /** Receive the open controller once mounted. */
  controllerRef?: (api: ScreenController) => void;
  /** Receive the focusable surface node so the facade's `focus()` can target it. */
  surfaceRef?: (el: HTMLElement) => void;
}

/** A stable id seed for labelling the dialog by its title. */
let idSeq = 0;

/**
 * Screen is the presentational full-bleed overlay surface. It owns the hard parts
 * of being a takeover: it fills its mount point while open, marks sibling
 * elements `inert` + `aria-hidden` (the standard modal pattern), moves focus into
 * the surface on open and restores it on close, fires `onBack` on Escape, and
 * runs an enter/exit transition that honors `prefers-reduced-motion`. When closed
 * it is removed from layout (no space, not focusable). The developer owns the swap
 * (their own routing flips `open`); this owns being the overlay.
 */
export function Screen(props: ScreenProps) {
  const [internalOpen, setInternalOpen] = createSignal(props.defaultOpen ?? false);
  const titleId = `kai-screen-title-${++idSeq}`;

  const isControlled = () => props.open !== undefined;
  const isOpen = () => (isControlled() ? !!props.open : internalOpen());
  const setOpen = (v: boolean) => {
    if (!isControlled()) setInternalOpen(v);
    props.onOpenChange?.(v);
  };

  props.controllerRef?.({ open: isOpen, setOpen });

  const presence = createPresence(isOpen);

  let surface: HTMLElement | undefined;
  // The element that had focus before we opened, restored on close.
  let restoreFocus: HTMLElement | null = null;
  // Siblings we inert-ed, so we can undo exactly what we did.
  let inerted: { el: HTMLElement; hadInert: boolean; hadAriaHidden: string | null }[] = [];

  const back = () => props.back !== false;

  const requestBack = () => props.onBack?.();

  // Inert + aria-hide the host's siblings while open (skip when noInert). This is
  // the one light-DOM touch: the standard modal pattern that makes the background
  // non-interactive and removes it from the a11y tree, which is what justifies the
  // dialog/aria-modal semantics on the surface.
  const applyInert = () => {
    if (props.noInert) return;
    const host = props.host?.();
    const parent = host?.parentElement;
    if (!host || !parent) return;
    for (const node of Array.from(parent.children)) {
      if (node === host) continue;
      const el = node as HTMLElement;
      inerted.push({ el, hadInert: el.hasAttribute('inert'), hadAriaHidden: el.getAttribute('aria-hidden') });
      el.setAttribute('inert', '');
      el.setAttribute('aria-hidden', 'true');
    }
  };
  const releaseInert = () => {
    for (const { el, hadInert, hadAriaHidden } of inerted) {
      if (!hadInert) el.removeAttribute('inert');
      if (hadAriaHidden === null) el.removeAttribute('aria-hidden');
      else el.setAttribute('aria-hidden', hadAriaHidden);
    }
    inerted = [];
  };

  // Drive inert + focus on the open/closed transition.
  createEffect((wasOpen: boolean) => {
    const open = isOpen();
    if (open && !wasOpen) {
      restoreFocus = (document.activeElement as HTMLElement) ?? null;
      applyInert();
      // Move focus into the surface once it has mounted.
      queueMicrotask(() => surface?.focus());
    } else if (!open && wasOpen) {
      releaseInert();
      // Return focus to the invoker if it's still in the document.
      const target = restoreFocus;
      restoreFocus = null;
      if (target && target.isConnected) queueMicrotask(() => target.focus());
    }
    return open;
    // Seed prev=false so a `defaultOpen` (open-at-mount) still runs the open branch.
  }, false);

  onCleanup(releaseInert);

  // Escape fires the back intent (navigation), matching the back button.
  const onKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Escape') {
      e.stopPropagation();
      requestBack();
    }
  };

  return (
    <Show when={presence.present()}>
      <div
        ref={(el) => { surface = el; presence.setRef(el); props.surfaceRef?.(el); }}
        part="body"
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        tabindex="-1"
        data-expanded={presence.state() === 'open' ? '' : undefined}
        data-closed={presence.state() === 'closed' ? '' : undefined}
        onKeyDown={onKeyDown}
        class={cn(
          'absolute inset-0 z-40 flex flex-col bg-background text-foreground outline-none',
          'animate-in fade-in-0 slide-in-from-bottom-2 motion-reduce:animate-none',
          'data-[closed]:animate-out data-[closed]:fade-out-0 data-[closed]:slide-out-to-bottom-2',
        )}
      >
        <header part="header" class="flex shrink-0 items-center gap-2 border-b border-border px-3 py-2">
          <Show when={back()}>
            <button
              part="back"
              type="button"
              aria-label="Back"
              class="inline-flex size-8 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
              onClick={requestBack}
            >
              <ArrowLeft size={16} aria-hidden="true" />
            </button>
          </Show>
          <h2 part="title" id={titleId} class="min-w-0 flex-1 truncate text-sm font-semibold text-foreground">
            {/* Native shadow-slot fallback: a projected `title` slot wins; otherwise
                the `title` prop renders as the slot's default content. */}
            {props.titleSlot ?? props.title}
          </h2>
          <div class="flex shrink-0 items-center gap-1">{props.actions}</div>
        </header>
        <div class="min-h-0 flex-1 overflow-auto">{props.children}</div>
      </div>
    </Show>
  );
}

// packages/ui/src/web-components/screen/screen.tsx
import { defineWebComponent } from '../define/define';
import { Screen, type ScreenController } from '../../components/screen/screen';
import { wireDisclosure } from '../disclosure/disclosure';

interface Props extends Record<string, unknown> {
  /** Drive/observe open state (Shoelace-style: settable + reflected to the `open`
   *  attribute; the element still self-manages). Set `el.open = true`, or
   *  `<kai-screen open>`; listen for `kai-open-change`. */
  open?: boolean;
  /** Initial open state on mount (uncontrolled seed). */
  defaultOpen?: boolean;
  /** Header title text. A projected `title` slot overrides it. (Named `headline`
   *  because `title` collides with the global `HTMLElement.title` attribute.) */
  headline?: string;
  /** Show the back button (default true). */
  back?: boolean;
  /** Opt out of marking sibling elements inert/aria-hidden while open (for unusual layouts). */
  noInert?: boolean;
}

/** Events fired by `<kai-screen>`. */
interface Events {
  /** Back navigation intent: the back button or Escape. The consumer flips their
   *  own routing in response (the screen knows nothing about the trigger). */
  'kai-back': Record<string, never>;
  /** The screen opened or closed (a method, `Escape` close, or driven `open`). */
  'kai-open-change': { open: boolean };
}

/**
 * `<kai-screen>` is a developer-swapped, full-bleed overlay destination: the
 * push/drill-in surface that takes over its mount point under a back-header. The
 * developer owns the swap (their own routing flips `open` in response to their
 * trigger button and the screen's `kai-back`); the screen owns being the takeover.
 *
 * It fills whatever it is mounted in (mount at the app root for a full takeover,
 * in a positioned region for a scoped one), marks sibling elements `inert` while
 * open (the standard modal pattern; opt out with `no-inert`), moves focus in on
 * open and restores it on close, and runs an enter/exit transition that honors
 * `prefers-reduced-motion`. `Escape` fires `kai-back`.
 *
 * ```html
 * <kai-screen headline="Design">
 *   <button slot="actions"><kai-avatar></kai-avatar></button>
 *   <div>…your surface…</div>
 * </kai-screen>
 * ```
 *
 * Open state is the standard disclosure surface: settable+reflecting `open`,
 * `kai-open-change`, and `show()`/`hide()`/`toggle()`; seed with `default-open`.
 * Parts: `header` · `back` · `title` · `body`.
 */
defineWebComponent<Props, Events>('kai-screen', {
  open: undefined,
  defaultOpen: undefined,
  headline: undefined,
  back: undefined,
  noInert: undefined,
}, (props, ctx) => {
  const { flag, element, dispatch, expose } = ctx;
  let api: ScreenController | undefined;
  let surface: HTMLElement | undefined;

  // The standard disclosure surface: settable+reflecting `open`, kai-open-change,
  // show/hide/toggle. See ./disclosure. This is the SOLE emitter of kai-open-change.
  wireDisclosure(ctx, () => api, () => props.open);

  // focus() shadows the host's native focus so it targets the screen surface
  // inside the shadow root (the WebAwesome/Shoelace convention).
  expose({
    /** Move focus to the screen surface (no-op while closed). */
    focus: (options?: FocusOptions) => surface?.focus(options),
  });

  return (
    <Screen
      defaultOpen={flag('defaultOpen')}
      back={!(props.back === false || element.getAttribute('back') === 'false')}
      noInert={flag('noInert')}
      host={() => element}
      titleSlot={<slot name="title">{props.headline as string | undefined}</slot>}
      actions={<slot name="actions" />}
      onBack={() => { dispatch('kai-back', {}); }}
      controllerRef={(a) => (api = a)}
      surfaceRef={(el) => (surface = el)}
    >
      <slot />
    </Screen>
  );
});
