// packages/ui/src/web-components/voice-output/voice-output.tsx
import { defineWebComponent } from '../define/define';
import { VoiceOutput, type VoiceOutputController } from '../../components/voice/voice-output';

interface Props extends Record<string, unknown> {
  /** The utterance to read aloud. */
  text?: string;
  /** Speak automatically when `text` is set/changed. */
  autoplay?: boolean;
  //
  // When set, the native `speechSynthesis` path is bypassed. Mirrors
  // `<kai-voice-input>`'s `transcribe`; a value-returning callback can't be modelled as a
  // fire-and-forget event, hence a property.
  /** TTS model seam the host supplies: given text, returns an audio `Blob`. **Function-valued property.** */
  synthesize?: (text: string) => Promise<Blob>;
  /** Disable the button (non-interactive). */
  disabled?: boolean;
}

/** Events fired by `<kai-voice-output>`. */
interface Events {
  // `speaking: true` fires when audio actually starts
  // (utterance.onstart natively; audio playback beginning on the `synthesize` path), not
  // when speak() is called; earlier releases fired it optimistically inside speak()
  // itself. Fires on real transitions only (manual click and programmatic
  // speak()/stop()), never on mount.
  /** Playback started or stopped. */
  'kai-speaking-change': { speaking: boolean };
  /** The model path (`synthesize`) resolved audio: the raw `Blob` before playback. */
  'kai-synthesized': { blob: Blob };
  // `detail.source` names the failing side (`recognition` on `<kai-voice-input>`,
  // `synthesis` on `<kai-voice-output>`), `detail.error` carries the platform error code,
  // the thrown exception's name, or `no-result` when recognition ended with no error and
  // no text (the user said nothing), and `detail.message` is human-readable. Deliberate
  // cancellation does not fire.
  /** A voice session failed, so no failure is ever silent. `detail.error` is the platform error code or the thrown name. */
  'kai-voice-error': { source: 'synthesis'; error: string; message: string };
}
// Native `speechSynthesis` by default; the `synthesize` property bypasses it and routes text
// through the host's own TTS model. The output sibling of `<kai-voice-input>`.
/**
 * A speaker button that reads text aloud.
 */
defineWebComponent<Props, Events>('kai-voice-output', {
  text: '',
  autoplay: false,
  synthesize: undefined,
  disabled: false,
}, (props, { dispatch, flag, expose }) => {
  // Pattern C: the VoiceOutput component owns playback; it hands up a
  // speak/pause/resume/stop controller. The facade captures it and exposes
  // delegating methods (manual + programmatic run the same path, so both emit
  // the same kai-speaking-change / kai-synthesized events).
  let controller: VoiceOutputController | undefined;
  expose({
    /** Speak the current `text` (native, or via `synthesize` if set). */
    speak: () => controller?.speak(),
    /** Pause playback (resumable). */
    pause: () => controller?.pause(),
    /** Resume paused playback. */
    resume: () => controller?.resume(),
    /** Stop playback and reset. */
    stop: () => controller?.stop(),
  });

  return (
    <VoiceOutput
      text={(props.text as string | undefined) ?? ''}
      autoplay={flag('autoplay')}
      disabled={flag('disabled')}
      onSynthesize={props.synthesize ? (text) => props.synthesize!(text) : undefined}
      onSpeakingChange={(speaking) => dispatch('kai-speaking-change', { speaking })}
      onSynthesized={(blob) => dispatch('kai-synthesized', { blob })}
      onError={(detail) => dispatch('kai-voice-error', detail)}
      controllerRef={(c) => (controller = c)}
    />
  );
});

// packages/ui/src/components/voice/voice-output.tsx
import { splitProps, Show, createSignal, createEffect, on, onCleanup } from 'solid-js';
import { cn } from '../utils/cn';
import { Button } from './button';
import { Tooltip } from './tooltip';
import { hasSpeechSynthesis, cancelSpeech, speakUtterance, pauseSpeech, resumeSpeech } from '../primitives/speech';

/** Imperative handle exposed via `controllerRef` — surfaces the playback controls
 *  so the `<kai-voice-output>` facade can forward them as instance methods. Both
 *  the native (speechSynthesis) and model (synthesize → Audio) paths run through
 *  these, so manual clicks and programmatic calls behave identically. */
export interface VoiceOutputController {
  /** Speak the current `text` (native by default, model if `synthesize` is set). */
  speak(): void;
  /** Pause playback (resumable). */
  pause(): void;
  /** Resume paused playback. */
  resume(): void;
  /** Stop playback and reset. */
  stop(): void;
}

export interface VoiceOutputProps {
  /** The utterance to read aloud. */
  text: string;
  /** Speak automatically when `text` is set/changed. */
  autoplay?: boolean;
  /** TTS model seam: given text, return an audio Blob to play. When set, the
   *  native speechSynthesis path is bypassed. Mirrors VoiceInput's `onTranscribe`. */
  onSynthesize?: (text: string) => Promise<Blob>;
  /** Fires whenever playback starts or stops. `speaking: true` means audio has
   *  actually started (utterance.onstart on the native path; audio.play()
   *  resolving on the model path), not that speak() was called. */
  onSpeakingChange?: (speaking: boolean) => void;
  /** Synthesis failed: a native utterance error, a rejecting `onSynthesize`, or
   *  audio playback failing to start. `error` is the platform error code or the
   *  exception's name. Deliberate cancellation (stop(), a new speak()) is not a
   *  failure and does not fire. The facade maps this to kai-voice-error. */
  onError?: (detail: { source: 'synthesis'; error: string; message: string }) => void;
  /** Fires once the model path resolves audio (model path only). */
  onSynthesized?: (blob: Blob) => void;
  disabled?: boolean;
  class?: string;
  /** Receive the imperative controller once mounted. The `<kai-voice-output>`
   *  facade forwards these as element methods (speak/pause/resume/stop). */
  controllerRef?: (controller: VoiceOutputController) => void;
}

export function VoiceOutput(props: VoiceOutputProps) {
  const [local] = splitProps(props, ['text', 'disabled', 'class']);
  const [isSpeaking, setIsSpeaking] = createSignal(false);
  const [isLoading, setIsLoading] = createSignal(false);

  // The model path plays through one reused <Audio>; the native path drives
  // speechSynthesis. Only one is live at a time (branch on onSynthesize).
  let audio: HTMLAudioElement | undefined;
  let objectUrl: string | undefined;
  let utterance: SpeechSynthesisUtterance | undefined;

  // No way to speak at all → render disabled. A model seam OR native synthesis
  // is enough; absent both, the control is inert (see the facade/spec).
  const capable = () => !!props.onSynthesize || hasSpeechSynthesis();

  const label = () =>
    isLoading() ? 'Synthesizing...' : isSpeaking() ? 'Stop' : 'Read aloud';

  function revokeUrl() {
    if (objectUrl) {
      URL.revokeObjectURL(objectUrl);
      objectUrl = undefined;
    }
  }

  // Native path: speechSynthesis.speak(new SpeechSynthesisUtterance(text)).
  // isSpeaking waits for utterance.onstart, so onSpeakingChange(true) means the
  // audio actually began. It used to flip optimistically before speak(), which
  // made "speaking" mean "speak() was called" and raced consumers watching for
  // playback to start (W4 symptom 3).
  function speakNative() {
    if (!hasSpeechSynthesis() || !local.text) return;
    cancelSpeech();
    utterance = new SpeechSynthesisUtterance(local.text);
    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = (event) => {
      setIsSpeaking(false);
      const code = event?.error ?? 'unknown';
      // `canceled`/`interrupted` are what the platform reports when the app
      // itself cancels (stop(), or a new speak() pre-empting): deliberate, not
      // a failure. Everything else surfaces (W4 traced a `not-allowed` here
      // that vanished without a word).
      if (code === 'canceled' || code === 'interrupted') return;
      props.onError?.({
        source: 'synthesis',
        error: code,
        message: `Speech synthesis error: ${code}`,
      });
    };
    speakUtterance(utterance);
  }

  // Model path: await onSynthesize(text) → play the Blob via an <Audio>.
  async function speakModel() {
    if (!props.onSynthesize || !local.text) return;
    setIsLoading(true);
    try {
      const blob = await props.onSynthesize(local.text);
      props.onSynthesized?.(blob);
      revokeUrl();
      objectUrl = URL.createObjectURL(blob);
      audio ??= new Audio();
      audio.src = objectUrl;
      audio.onended = () => setIsSpeaking(false);
      audio.onerror = () => {
        setIsSpeaking(false);
        props.onError?.({
          source: 'synthesis',
          error: 'playback-failed',
          message: 'The synthesized audio failed to play',
        });
      };
      await audio.play();
      // play() resolving is this path's "audio actually started" (the model
      // path's counterpart of utterance.onstart), so isSpeaking flips only now.
      setIsSpeaking(true);
    } catch (err) {
      // onSynthesize rejected, or play() did (e.g. NotAllowedError under an
      // autoplay policy). Either way the reply is silent: say so.
      setIsSpeaking(false);
      props.onError?.({
        source: 'synthesis',
        error: err instanceof Error ? err.name : 'unknown',
        message: err instanceof Error ? err.message : String(err),
      });
    } finally {
      setIsLoading(false);
    }
  }

  function speak() {
    if (props.onSynthesize) void speakModel();
    else speakNative();
  }

  function stop() {
    if (props.onSynthesize) {
      if (audio) {
        audio.pause();
        audio.currentTime = 0;
      }
    } else {
      cancelSpeech();
    }
    setIsSpeaking(false);
  }

  function pause() {
    if (props.onSynthesize) audio?.pause();
    else pauseSpeech();
  }

  function resume() {
    if (props.onSynthesize) void audio?.play();
    else resumeSpeech();
  }

  function handleClick() {
    if (isSpeaking()) stop();
    else speak();
  }

  // Emit speaking transitions to the host. `defer: true` skips the spurious
  // initial `false` — only real start/stop transitions fire.
  createEffect(on(isSpeaking, (speaking) => {
    props.onSpeakingChange?.(speaking);
  }, { defer: true }));

  // Autoplay: speak when text first arrives / changes (defer skips the mount
  // value so an empty seed doesn't speak).
  createEffect(on(() => local.text, (text) => {
    if (props.autoplay && text) speak();
  }, { defer: true }));

  props.controllerRef?.({ speak, pause, resume, stop });

  onCleanup(() => {
    stop();
    revokeUrl();
  });

  // Speaker icon (idle)
  const SpeakerIcon = () => (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5" />
      <path d="M19.07 4.93a10 10 0 010 14.14M15.54 8.46a5 5 0 010 7.07" />
    </svg>
  );

  // Square stop icon (speaking)
  const StopIcon = () => (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
      <rect x="4" y="4" width="16" height="16" rx="2" />
    </svg>
  );

  // Spinner (model synthesis in flight)
  const Spinner = () => (
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="animate-spin">
      <path d="M21 12a9 9 0 11-6.219-8.56" />
    </svg>
  );

  return (
    <div class={cn('relative inline-flex items-center justify-center', local.class)}>
      <Tooltip content={label()}>
        <Button
          part="button"
          variant="ghost"
          size="icon-sm"
          aria-label={label()}
          aria-pressed={isSpeaking()}
          onClick={handleClick}
          disabled={local.disabled || !capable() || isLoading()}
          class={cn('relative z-10 rounded-full transition-all duration-300')}
        >
          <Show when={isLoading()}>
            <Spinner />
          </Show>
          <Show when={!isLoading() && isSpeaking()}>
            <StopIcon />
          </Show>
          <Show when={!isLoading() && !isSpeaking()}>
            <SpeakerIcon />
          </Show>
        </Button>
      </Tooltip>
    </div>
  );
}
