// src/ui/progress-bar.tsx
import { type JSX, Show, splitProps } from 'solid-js';
import { cn } from '../utils/cn';

export type ProgressTone = 'primary' | 'success' | 'warning' | 'error' | 'info';

/** Fill hue per `tone`. `primary` is the theme accent; the rest use the kit's
 *  tool hues (the same colors as kai-status / kai-notice). */
export const TONE_FILL: Record<ProgressTone, string> = {
  primary: 'bg-primary',
  success: 'bg-tool-green',
  warning: 'bg-tool-amber',
  error: 'bg-tool-red',
  info: 'bg-tool-blue',
};

export interface ProgressBarProps extends JSX.HTMLAttributes<HTMLDivElement> {
  /** Current progress value (0..max). */
  value: number;
  /** The value `value` runs to. Defaults to 100. */
  max?: number;
  /** Optional caption above the track. */
  label?: string;
  /** Fill color. Defaults to `primary`. Override via `::part(fill)` for custom hues. */
  tone?: ProgressTone;
}

/**
 * A thin determinate progress bar: a rounded track with a `bg-primary` fill whose
 * width is `value / max`, clamped to 0..100%. Theme-aware (track = `bg-surface-strong`,
 * fill = `bg-primary`). Set `tone` for a semantic fill hue. Restyle via
 * `::part(track)` / `::part(fill)`. The fill width transitions smoothly under
 * `prefers-reduced-motion: no-preference`.
 */
export function ProgressBar(props: ProgressBarProps) {
  const [local, rest] = splitProps(props, ['value', 'max', 'label', 'tone', 'class']);
  const max = () => local.max ?? 100;
  // Clamp value into [0, max]; drive both the fill width and aria-valuenow off it
  // so the bar and the announced value stay consistent.
  const clamped = () => {
    const m = max();
    if (!(m > 0)) return 0;
    return Math.max(0, Math.min(local.value, m));
  };
  const percent = () => {
    const m = max();
    return m > 0 ? (clamped() / m) * 100 : 0;
  };
  return (
    <div class={cn('flex flex-col gap-1', local.class)} {...rest}>
      <Show when={local.label}>
        <span class="text-xs text-muted-foreground">{local.label}</span>
      </Show>
      <div
        part="track"
        role="progressbar"
        aria-valuenow={clamped()}
        aria-valuemin={0}
        aria-valuemax={max()}
        aria-label={local.label}
        class="h-1.5 w-full overflow-hidden rounded-full bg-surface-strong"
      >
        <div
          part="fill"
          class={cn(
            'h-full rounded-full motion-safe:transition-[width] motion-safe:duration-500 motion-safe:ease-out',
            TONE_FILL[local.tone ?? 'primary'],
          )}
          style={{ width: `${percent()}%` }}
        />
      </div>
    </div>
  );
}

// packages/ui/src/web-components/progress-bar/progress-bar.tsx
import { ProgressBar, type ProgressTone } from '../../components/progress/progress-bar';
import { defineWebComponent } from '../define/define';

interface Props extends Record<string, unknown> {
  /** Current progress value (0..max). Attribute: `value`. */
  value?: number;
  /** The value `value` runs to (default 100). Attribute: `max`. */
  max?: number;
  /** Optional caption above the track. Attribute: `label`. */
  label?: string;
  /** Fill color: `primary` (default), `success`, `warning`, `error`, `info`. Attribute: `tone`. */
  tone?: string;
}

/**
 * `<kai-progress-bar>` — a thin determinate progress bar: a rounded track with a
 * `bg-primary` fill whose width is `value / max` (clamped to 0..100%). Set `tone`
 * for a semantic fill hue. Scalar attributes only.
 *
 * ```html
 * <kai-progress-bar value="66"></kai-progress-bar>
 * <kai-progress-bar value="3" max="5" label="Setup"></kai-progress-bar>
 * <kai-progress-bar value="60" tone="success"></kai-progress-bar>
 * ```
 * Restyle via `::part(track)` / `::part(fill)`.
 */
defineWebComponent<Props>('kai-progress-bar', {
  value: undefined,
  max: undefined,
  label: undefined,
  tone: 'primary',
}, (props) => (
  <ProgressBar
    value={props.value != null ? Number(props.value) : 0}
    max={props.max != null ? Number(props.max) : undefined}
    label={props.label as string | undefined}
    tone={props.tone as ProgressTone | undefined}
  />
));
