// src/ui/agent-card.tsx
import { type JSX, Show, splitProps } from 'solid-js';
import { Bell, MoreHorizontal } from 'lucide-solid';
import { cn } from '../utils/cn';

/** The run state of an agent, mapped to the kit's tool / status hues.
 *  - `working` (blue) the agent is actively running.
 *  - `idle` (muted) waiting, no current activity.
 *  - `done` (green) finished its turn.
 *  - `error` (red) failed.
 *  - `blocked` (amber) stalled, usually waiting on something. */
export type AgentStatusTone = 'working' | 'idle' | 'done' | 'error' | 'blocked';

export interface AgentStatus {
  /** Which hue the status dot takes. */
  tone: AgentStatusTone;
  /** Optional short label rendered next to the dot (e.g. "Working", "Blocked on you"). */
  label?: string;
  /** Animate the dot with a ping ring (off under prefers-reduced-motion). */
  pulse?: boolean;
}

export interface AgentCardProps {
  /** @deprecated No longer rendered. Kept for back-compat with existing callers. */
  leading?: JSX.Element;
  /** The agent's name. The primary label. */
  name: string;
  /** @deprecated No longer rendered. Kept for back-compat with existing callers. */
  subtitle?: string;
  /** @deprecated No longer rendered. Kept for back-compat with existing callers. */
  lastLine?: string;
  /** Run status: a tone-colored dot, an optional small label, optionally pulsing. */
  status: AgentStatus;
  /** Raise a prominent "needs you" pill plus a glowing amber edge. The
   *  attention-routing signal that pulls focus to this agent. */
  needsAttention?: boolean;
  /** Selected / focused state. Highlighted border and surface. */
  active?: boolean;
  /** Promote this agent to focus. Fires on click and on Enter / Space. */
  onActivate?: () => void;
  /** Alias for {@link AgentCardProps.onActivate}. Both fire if both are set. */
  onClick?: () => void;
  /** Show a trailing "..." overflow button and fire this on click. The consumer
   *  wires the actual menu; the card only surfaces the affordance. Click is
   *  stopped from also activating the card. */
  onMenu?: (e: MouseEvent) => void;
  /** Extra classes merged over the card. */
  class?: string;
}

/** tone -> dot background utility (the kit's tool hues + muted for idle). */
const TONE_DOT: Record<AgentStatusTone, string> = {
  working: 'bg-tool-blue',
  idle: 'bg-muted-foreground',
  done: 'bg-tool-green',
  error: 'bg-tool-red',
  blocked: 'bg-tool-amber',
};

/** tone -> matching text color for the inline status label. */
const TONE_TEXT: Record<AgentStatusTone, string> = {
  working: 'text-tool-blue',
  idle: 'text-muted-foreground',
  done: 'text-tool-green',
  error: 'text-tool-red',
  blocked: 'text-tool-amber',
};

/** Default accessible name per tone, used when no `status.label` is given so the
 *  state is still announced even when the dot reads as decorative. */
const TONE_LABEL: Record<AgentStatusTone, string> = {
  working: 'Working',
  idle: 'Idle',
  done: 'Done',
  error: 'Error',
  blocked: 'Blocked',
};

/**
 * AgentCard - the compact representation of one agent in a multi-agent workspace.
 *
 * In a focus + periphery layout the agents you are not focused on collapse to these
 * glanceable cards, arranged as a narrow side RAIL or a wide LIST. The card stays
 * deliberately minimal: the agent name, a tone-colored status dot, a "needs you"
 * affordance when the agent wants your attention, and a trailing "..." overflow
 * button for per-agent actions. Clicking the card promotes the agent back to focus.
 *
 * It is `w-full` and lets the name truncate, so the same component works in both a
 * narrow rail and a wide list without changes - the content adapts to the box.
 *
 * Status maps to the kit's tool hues so it reads in light and dark from tokens alone:
 * working = blue, idle = muted, done = green, error = red, blocked = amber. Setting
 * `needsAttention` raises an amber "Needs you" pill and a glowing amber ring so the
 * card jumps out of the periphery - the attention-routing signal.
 */
export function AgentCard(props: AgentCardProps) {
  const [local] = splitProps(props, [
    'name',
    'status',
    'needsAttention',
    'active',
    'onActivate',
    'onClick',
    'onMenu',
    'class',
    // leading/subtitle/lastLine are accepted but no longer rendered (back-compat).
    'leading',
    'subtitle',
    'lastLine',
  ]);

  const tone = (): AgentStatusTone => local.status.tone;
  const activate = () => {
    local.onActivate?.();
    local.onClick?.();
  };

  return (
    // role="button" rather than a real <button> so the trailing kebab <button>
    // is a valid (non-nested) interactive element.
    <div
      role="button"
      tabindex="0"
      onClick={activate}
      onKeyDown={(e) => {
        // Only activate from the card itself, never from the nested kebab.
        if (e.currentTarget !== e.target) return;
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          activate();
        }
      }}
      aria-current={local.active ? 'true' : undefined}
      data-active={local.active ? '' : undefined}
      data-needs-attention={local.needsAttention ? '' : undefined}
      class={cn(
        'group flex w-full cursor-pointer items-center gap-3 rounded-lg border px-3 py-2.5 text-left',
        'outline-none transition-[background-color,border-color,box-shadow]',
        'focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring',
        local.active
          ? 'border-primary bg-accent'
          : 'border-border bg-surface hover:bg-accent',
        // The attention edge: a glowing amber ring + tinted border. Stacks over the
        // active/idle surface so a focused agent can still flag that it needs you.
        local.needsAttention && 'border-tool-amber/50 ring-2 ring-inset ring-tool-amber/60',
        local.class,
      )}
    >
      {/* Status indicator leads, immediately before the name: [● label?] Name. */}
      <span
        class="inline-flex shrink-0 items-center gap-1.5"
        role="status"
        aria-label={local.status.label ?? TONE_LABEL[tone()]}
      >
        <span class="relative inline-flex">
          <Show when={local.status.pulse}>
            <span
              aria-hidden="true"
              class={cn(
                'absolute inline-flex h-full w-full animate-ping rounded-full opacity-75 motion-reduce:hidden',
                TONE_DOT[tone()],
              )}
            />
          </Show>
          <span
            aria-hidden="true"
            part="status"
            class={cn('relative inline-block size-2 rounded-full', TONE_DOT[tone()])}
          />
        </span>
        <Show when={local.status.label}>
          <span class={cn('text-[11px] font-medium leading-none', TONE_TEXT[tone()])}>
            {local.status.label}
          </span>
        </Show>
      </span>

      <span class="truncate text-sm font-medium leading-tight text-foreground min-w-0 flex-1">
        {local.name}
      </span>

      <span class="flex shrink-0 items-center gap-2">
        <Show when={local.needsAttention}>
          <span class="inline-flex items-center gap-1 rounded-full bg-tool-amber/15 px-2 py-0.5 text-[11px] font-medium text-tool-amber">
            <Bell class="size-3" aria-hidden="true" />
            Needs you
          </span>
        </Show>

        <Show when={local.onMenu}>
          <button
            type="button"
            part="menu"
            aria-label="More"
            onClick={(e) => {
              // Don't let the menu click also activate the card.
              e.stopPropagation();
              local.onMenu?.(e);
            }}
            class={cn(
              'inline-flex size-7 shrink-0 items-center justify-center rounded-md',
              'text-muted-foreground outline-none transition-colors',
              'hover:bg-surface-sunken hover:text-foreground',
              'focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-ring',
            )}
          >
            <MoreHorizontal class="size-4" aria-hidden="true" />
          </button>
        </Show>
      </span>
    </div>
  );
}

// packages/ui/src/elements/agent-card.tsx
import { defineWebComponent } from './define';
import { AgentCard, type AgentStatus } from '../components/agent-card';

interface Props extends Record<string, unknown> {
  /** The agent's name, the primary label. Attribute: `name`. */
  name?: string;
  /** Selected / focused state: highlighted border + surface. Attribute: `active`. */
  active?: boolean;
  /** Raise a prominent "Needs you" pill plus a glowing amber edge. This
   *  is the attention-routing signal that pulls focus to this agent.
   *  Attribute: `needs-attention`. */
  needsAttention?: boolean;
  /** Run status. A JS PROPERTY (object), not an attribute. Shape: `{ tone,
   *  label?, pulse? }`, where `tone` is one of `working` | `idle` | `done` |
   *  `error` | `blocked` (maps to the kit's tool hues), `label` is an optional
   *  short string beside the dot, and `pulse` animates the dot. Set it with
   *  `el.status = { tone: 'working', label: 'Working', pulse: true }`. */
  status?: AgentStatus;
}

/** Events fired by `<kai-agent-card>`. */
interface Events {
  /** The card was activated by a click, or by Enter / Space while focused.
   *  Promote this agent back to focus. */
  'kai-activate': void;
  /** The trailing "..." kebab was clicked. The consumer opens its own menu; the
   *  card only surfaces the affordance (the click does not also activate the card). */
  'kai-menu': void;
}

/**
 * `<kai-agent-card>` — the compact glanceable card for one agent in a multi-agent
 * workspace. The agent name with a leading tone-colored status dot, an optional
 * "Needs you" attention treatment, an `active` (selected) state, and a trailing
 * "..." overflow button.
 *
 * Set `status` as a JS property (it's an object); `name` is a string attribute and
 * `active` / `needs-attention` are boolean attributes. Listen for `kai-activate`
 * (promote to focus) and `kai-menu` (open your own per-agent menu).
 *
 * ```html
 * <kai-agent-card name="Refactor bot" active></kai-agent-card>
 * <script type="module">
 *   import '@kitn.ai/ui/elements';
 *   const card = document.querySelector('kai-agent-card');
 *   card.status = { tone: 'working', label: 'Working', pulse: true };
 *   card.addEventListener('kai-activate', () => focusAgent());
 *   card.addEventListener('kai-menu', () => openMenu());
 * </script>
 * ```
 * Recolor the status dot via `::part(status)` and the kebab via `::part(menu)`.
 */
defineWebComponent<Props, Events>('kai-agent-card', {
  name: undefined,
  active: undefined,
  needsAttention: undefined,
  status: undefined,
}, (props, { dispatch, flag }) => (
  <AgentCard
    name={(props.name as string) ?? ''}
    active={flag('active')}
    needsAttention={flag('needsAttention')}
    status={(props.status as AgentStatus) ?? { tone: 'idle' }}
    onActivate={() => dispatch('kai-activate')}
    onMenu={() => dispatch('kai-menu')}
  />
));
