// packages/ui/src/components/row/row-group.tsx
import { splitProps, type JSX } from 'solid-js';
import { cn } from '../../utils/cn';

/**
 * `RowGroup`, the frame that turns loose rows into a LIST: one bordered, rounded
 * card with a hairline between adjacent rows, the first row rounded at the top
 * only, the last at the bottom only, and every middle row square. It is the shape
 * a settings screen, a link list and a home tab all hand-rolled before it existed
 * (`row.stories.tsx`, `settings-group.tsx`, `home-panel.tsx`: the last two also
 * had to fight `Row`'s own standalone radius with `rounded-none border-b
 * last:border-b-0`).
 *
 * COMPOSITION ONLY. It takes children, not `items`: which rows exist, in what
 * order, keyed how, and what an empty list means are the application's business
 * (a data-driven list would also have to own loading, empty and error states,
 * which is a component library deciding policy it cannot see). Rows are authored
 * by the caller and this only frames them.
 *
 * It renders NO geometry itself; see the row-list block in `../kit-base.css` for
 * the dividers, the per-position corners and the reasons they are CSS rather
 * than classes. Two consequences worth knowing at the call site:
 *
 * - Rows must be DIRECT CHILDREN. Both rule sets are direct-child selectors, so a
 *   wrapper element per row (a `<li>`, a slide-in transition container) collects
 *   the divider on its own box and the rows inside it get none.
 * - Rows are MOUNTED AND UNMOUNTED rather than hidden. `hidden` leaves the row in
 *   the sibling chain and the next row's hairline lands under the frame's top
 *   border; that limit is explained where the rule lives.
 *
 * The frame's own chrome (border, radius, clip) is a plain class, overridable
 * through `class` like any other kit part: a group inside a rounded panel passes
 * `rounded-none border-0` and one that should read as flush sets
 * `[--kai-row-radius:0]`.
 */
export interface RowGroupProps extends Omit<JSX.HTMLAttributes<HTMLDivElement>, 'ref'> {
  /** The rows, as direct children. */
  children?: JSX.Element;
  class?: string;
}

export function RowGroup(props: RowGroupProps) {
  const [local, rest] = splitProps(props, ['children', 'class']);

  return (
    <div
      part="group"
      {...rest}
      // `kai-row-group` is load-bearing, not decoration: every divider and corner
      // rule in kit-base.css is keyed on it. Renaming it here without renaming it
      // there renders a group with no dividers and no rounding at all, silently.
      class={cn('kai-row-group overflow-hidden rounded-xl border border-border', local.class)}
    >
      {local.children}
    </div>
  );
}

// packages/ui/src/elements/row-group.tsx
import { defineWebComponent } from './define';
import { RowGroup } from '../ui/row-group';

type Props = Record<string, unknown>;

/**
 * `<kai-row-group>`: the frame that turns loose `<kai-row>`s into a list — one
 * bordered, rounded card, a hairline between adjacent rows, the first rounded at
 * the top only and the last at the bottom only.
 *
 * COMPOSITION ONLY: put your rows in as light-DOM children (the default slot).
 * There is no data mode — which rows exist, in what order, and what an empty list
 * means are the application's business.
 *
 * ```html
 * <kai-row-group>
 *   <kai-row chevron interactive>Preferences</kai-row>
 *   <kai-row chevron interactive>Connected repos</kai-row>
 * </kai-row-group>
 * ```
 *
 * Two rules it inherits from how the geometry reaches a shadow boundary, both
 * stated because neither is discoverable from the markup:
 *
 * - Rows must be DIRECT CHILDREN. Wrap one in a `<div>` (or any other element) and
 *   the divider and the corners land on that wrapper rather than on the row
 *   inside it.
 * - Rows are added and REMOVED rather than hidden with the `hidden` attribute: a
 *   hidden row still occupies its place in the sibling chain, so the row after it
 *   paints a hairline at the very top of the frame. `::slotted()` cannot express
 *   "preceded by a visible sibling" (it takes a compound selector, never a
 *   combinator), so this is a limit of the platform here rather than a pending
 *   fix.
 *
 * `--kai-row-radius` on the host is the list's corner-radius knob (default: the
 * `--radius-lg` token, the same scale a standalone row rounds on). Set it to `0`
 * for a group that should sit flush inside a panel that is already rounded.
 *
 * ACCESSIBILITY: the frame carries no role of its own, deliberately. When the
 * rows are a meaningful cluster of related things rather than a plain list of
 * links, label it yourself — `<kai-row-group role="group" aria-label="Preferences">`
 * — which is exactly the choice `Row` makes about its own root element. Both
 * attributes pass straight through to the frame.
 */
defineWebComponent<Props>('kai-row-group', {}, () => (
  <>
    {/* Same reason as `<kai-view>`: the shared base sheet sets `:host{display:block}`,
        an author rule that outranks the UA's `[hidden]{display:none}`, so without
        this a hidden group still lays out. */}
    <style>{':host([hidden]){display:none}'}</style>
    <RowGroup>
      <slot />
    </RowGroup>
  </>
));
