// packages/ui/src/components/kbd/kbd-group.tsx
import { splitProps, type JSX } from 'solid-js';
import { cn } from '../../utils/cn';

/**
 * `KbdGroup` — lays several separate `Kbd`s out as one shortcut hint. Reach for it
 * when the caps come from MORE THAN ONE shortcut or from a typed sequence
 * (`<KbdGroup><Kbd keys="Mod+K" /><Kbd keys="Mod+S" /></KbdGroup>`), because a
 * `keys` token spec is a single shortcut and cannot express where one ends and the
 * next begins. A lone `Kbd` already renders its own token row with the same gap
 * (`gap-0.5` between caps of one chip), so it needs no group.
 *
 * Composition only: which shortcuts exist and in what order is the caller's
 * business, exactly as `RowGroup` takes children rather than `items`. Nothing here
 * binds keys — `Kbd` is display only.
 */
export interface KbdGroupProps extends JSX.HTMLAttributes<HTMLElement> {
  class?: string;
}

export function KbdGroup(props: KbdGroupProps): JSX.Element {
  const [local, rest] = splitProps(props, ['children', 'class']);

  return (
    <div
      part="group"
      // The props type extends `JSX.HTMLAttributes<HTMLElement>`, so `rest.ref` is an
      // `HTMLElement` while this frame is a `div`; the spread narrows it here rather
      // than on the public type two lanes code against. Runtime is unaffected — Solid
      // hands the ref the element it actually mounted.
      {...(rest as JSX.HTMLAttributes<HTMLDivElement>)}
      class={cn('inline-flex items-center gap-1', local.class)}
    >
      {local.children}
    </div>
  );
}

// packages/ui/src/web-components/kbd/kbd-group.tsx
import { defineWebComponent } from '../define/define';
import { KbdGroup } from '../../components/kbd/kbd-group';

type Props = Record<string, unknown>;

/**
 * `<kai-kbd-group>` — lays several separate `<kai-kbd>`s out as one shortcut hint.
 * Use it when the caps come from more than one shortcut or from a typed sequence;
 * a `keys` token spec is a single shortcut and cannot say where one ends and the
 * next begins. A lone `<kai-kbd keys="Mod+K">` already renders its own token row,
 * so it needs no group.
 *
 * Slot your `<kai-kbd>`s in as light-DOM children (the default slot). No props.
 *
 * ```html
 * <kai-kbd-group>
 *   <kai-kbd keys="Mod+K"></kai-kbd>
 *   <kai-kbd keys="Mod+S"></kai-kbd>
 * </kai-kbd-group>
 * <kai-kbd-group>
 *   <kai-kbd>G</kai-kbd>
 *   <kai-kbd>D</kai-kbd>
 * </kai-kbd-group>
 * ```
 *
 * Restyle the flex frame (it owns the gap between the kbd elements) via
 * `::part(group)`, and each cap via `::part(key)` on the `<kai-kbd>` itself.
 */
defineWebComponent<Props>('kai-kbd-group', {}, () => (
  <>
    {/* Base sets `:host{display:block}`; a shortcut hint flows inline like a chip,
        matching `<kai-kbd>`'s own host rule, so the group can sit in a sentence. */}
    <style>{':host{display:inline-flex}'}</style>
    <KbdGroup>
      <slot />
    </KbdGroup>
  </>
));
